#!/bin/bash

echo "🚀 Starting Spring Boot Customer Dashboard Application"
echo "=================================================="

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo "❌ Docker is not installed. Please install Docker first."
    exit 1
fi

# Check if Docker Compose is installed
if ! command -v docker-compose &> /dev/null; then
    echo "❌ Docker Compose is not installed. Please install Docker Compose first."
    exit 1
fi

echo "✅ Docker and Docker Compose are available"

# Start the application using Docker Compose
echo "🐳 Starting services with Docker Compose..."
docker-compose up -d

echo ""
echo "⏳ Waiting for services to start..."
sleep 10

echo ""
echo "🎉 Application is starting up!"
echo ""
echo "📋 Available Features:"
echo "====================="
echo "🔐 Authentication System"
echo "   - User registration and login"
echo "   - JWT token-based authentication"
echo "   - Protected routes"
echo ""
echo "👥 Customer Management"
echo "   - Create, read, update, delete customers"
echo "   - Customer profile pictures with S3 upload"
echo "   - Search and filter customers"
echo "   - Customer cards with modern UI"
echo ""
echo "📊 Customer Analytics"
echo "   - Customer statistics and insights"
echo "   - Data visualization"
echo ""
echo "📁 Export/Import System"
echo "   - Export customer data to CSV"
echo "   - Import customer data from CSV"
echo "   - Bulk data operations"
echo ""
echo "📝 Activity Logging"
echo "   - Track customer activities"
echo "   - Activity timeline view"
echo "   - Activity history and audit trail"
echo ""
echo "🔔 Notification Center"
echo "   - Real-time customer notifications"
echo "   - Different notification types and priorities"
echo "   - Bulk notification sending"
echo "   - Notification management (read/unread, delete)"
echo "   - Customer-specific notification views"
echo ""
echo "🌐 Access Points:"
echo "================"
echo "Frontend (React): http://localhost:3000"
echo "Backend API: http://localhost:8080"
echo "Database: localhost:5432"
echo ""
echo "🔧 API Endpoints:"
echo "================"
echo "POST /api/v1/auth/register - Register new user"
echo "POST /api/v1/auth/login - User login"
echo "GET /api/v1/customers - Get all customers"
echo "POST /api/v1/customers - Create customer"
echo "PUT /api/v1/customers/{id} - Update customer"
echo "DELETE /api/v1/customers/{id} - Delete customer"
echo "GET /api/v1/customers/export - Export customers to CSV"
echo "POST /api/v1/customers/import - Import customers from CSV"
echo "GET /api/v1/customers/activities - Get customer activities"
echo "GET /api/v1/customers/{id}/notifications - Get customer notifications"
echo "POST /api/v1/customers/notifications/bulk - Send bulk notifications"
echo ""
echo "📱 Frontend Routes:"
echo "=================="
echo "/ - Dashboard home"
echo "/customers - Customer management"
echo "/export-import - Export/Import functionality"
echo "/activities - Activity timeline"
echo "/notifications - Notification center"
echo ""
echo "🛑 To stop the application:"
echo "docker-compose down"
echo ""
echo "📝 Logs:"
echo "docker-compose logs -f"
echo ""
echo "🎯 Default credentials:"
echo "Username: admin@admin.com"
echo "Password: password"
echo ""
echo "✨ Happy coding! ✨" 